### ISSUE TITLE
Usage Documentation 

### ISSUE THREAD

**Issue by adityagu0910** [Wolfereign/ansible_role_firewalld#1]
Hi @Wolfereign 

I wanted to try this role as it looks amazing .
Could you please explain usage a little if it is possible for you? 

Thanks !!

**Comment by dhimanha** [comment]
Hi @Wolfereign , It would be great if you could  put instructions related to playbook usages.

Thanks

**Comment by Wolfereign** [comment]
I abandoned this role some time ago but i'm going to go ahead and finally archive it. The reasons it was abandoned is due to flaws in the design of firewalld. Zones, while appealing in theory, add a layer of complexity to firewall management that is more harmfull then helpfull. To make matters worse when nftables is the firewalld backend the firewalld rules can be completely bypassed by other nftables tables. firewalld has no builtin way to handle this and have stated it was done this way by design. This is just my conjecture from experience working with firewalld, iptables, and nftables.

My reccomendation, with as little weight as it may have, is to reduce the complexity of your firewall and use iptables or nftables directly. Both tools are easyer to take full control with ansible and, unlike firewalld, can act as the single source of truth for your host-based firewall.

**Comment by Wolfereign** [comment]
The same concepts that this role uses can be applied to both nftables and iptables.  A main design principle of this role was for it to act as a single source of truth for the firewall.  This is so you can assure the exact state of the firewall after every run and when configuration is removed the firewall is updated to reflect that removal.  Other Ansible firewall roles tend to not consider system state or how to handle the removal of firewall rules that are no longer desired.

In the future I may upload a better documented role based on nftables but I am hoping for something that can handle docker and other container technologies to come along.
